package circuits

import (
	"fmt"
	"os/exec"
	"strings"
)

// AssertToolchain verifies that the installed nargo and bb versions on the host
// match the versions the embedded artifacts were built with. Call this at bundler
// startup and fail fast on mismatch — proofs generated by a different bb version
// may not verify against the embedded VK.
//
// Usage:
//
//	if err := circuits.AssertToolchain(); err != nil {
//	    log.Fatalf("toolchain mismatch: %v", err)
//	}
func AssertToolchain() error {
	meta, err := JWTMetadata()
	if err != nil {
		return fmt.Errorf("load metadata: %w", err)
	}
	if err := assertVersion("nargo", meta.Toolchain.Nargo); err != nil {
		return err
	}
	if err := assertVersion("bb", meta.Toolchain.BB); err != nil {
		return err
	}
	return nil
}

func assertVersion(tool, expected string) error {
	out, err := exec.Command(tool, "--version").CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s --version: %w", tool, err)
	}
	actual := strings.TrimSpace(string(out))
	if !strings.Contains(actual, expected) {
		return fmt.Errorf(
			"%s version mismatch: expected %q, got %q (install from the signet-circuits toolchain Docker image or run ./scripts/install-toolchain.sh)",
			tool, expected, actual,
		)
	}
	return nil
}
